// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9UL92Rlu1B89xK2EcMLu_TMZRMnFBmA',
    appId: '1:51663830731:web:d35931f25be6001d38254e',
    messagingSenderId: '51663830731',
    projectId: 'eco-minder-pervasive',
    authDomain: 'eco-minder-pervasive.firebaseapp.com',
    storageBucket: 'eco-minder-pervasive.appspot.com',
    measurementId: 'G-QG0PFKQEWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-I53HJfjN9jHvClO9AwakIvbR9Iopc0',
    appId: '1:51663830731:android:b7c2878d81ef4cc038254e',
    messagingSenderId: '51663830731',
    projectId: 'eco-minder-pervasive',
    storageBucket: 'eco-minder-pervasive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrTj3N1SMas4p8om110tPCujXT8wav3s',
    appId: '1:51663830731:ios:84dd2db290d6b82f38254e',
    messagingSenderId: '51663830731',
    projectId: 'eco-minder-pervasive',
    storageBucket: 'eco-minder-pervasive.appspot.com',
    iosClientId: '51663830731-1v58p1lk94moaso87u0lug87feck6gnj.apps.googleusercontent.com',
    iosBundleId: 'com.squid99.eco-minder-pervasive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrTj3N1SMas4p8om110tPCujXT8wav3s',
    appId: '1:51663830731:ios:d326504d38beabf338254e',
    messagingSenderId: '51663830731',
    projectId: 'eco-minder-pervasive',
    storageBucket: 'eco-minder-pervasive.appspot.com',
    iosClientId: '51663830731-is3lbp7d6pou0kv5b7q5i352ui47d4r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoMinderFlutterApp',
  );
}
